### ISSUE TITLE
FeatureFlagSetLD controller 0.7.7 failing to send identityRef to LD for evaluation.

### ISSUE THREAD

**Issue by acbodine** [razee-io/FeatureFlagSetLD#317]
**Describe the bug**
When we updated from 0.7.6 to 0.7.7 we started observing incorrect values in ffsld objects based on configured target rules in LD. Turns out we were falling through to the default variations, despite the ffsld specifying an identifyRef (unchanged for over a year) and matching target rules in LD (also unchanged for a long time).

**To Reproduce**
1. Get ffsld controller at 0.7.6 or before, and ffsld with some flag matching a target rule in LD so you're served a variation other than the default.
2. Update ffsld controller to 0.7.7 and observe your now getting the default variation.

**Expected behavior**
Pass the identifyRef along with the request to LD.

**Screenshots**

**Kubernetes Version (kubectl version):**
 - Client: 1.20
 - Server: 1.20

**Additional context**

**Comment by alewitt2** [comment]
during this update we went from razeedeploy-core [0.13.1 to 0.14.1](https://github.com/razee-io/razeedeploy-core/compare/0.13.1...0.14.1) this shouldnt have effected you, but im guessing there is an issue, because in this change we reworked the fetchEnvs module. This would seem to track with the behavior you are seeing, im guessing you are falling through to the default becuase its not finding/sending the identityRef that it used to be able to fetch.

would you be able to share your identity ref so i can try to debug further?

**Comment by alewitt2** [comment]
using the following to debug
```yaml
apiVersion: deploy.razee.io/v1alpha2
kind: FeatureFlagSetLD
metadata:
  name: razeedeploy-test
  namespace: razeedeploy
spec:
  sdkKey: "sdk-xxxxx-xxxx-xxxxxx-xxxx"
  identityRef:
    env:
      - name: region
        value: us-south
```
i was able to confirm
1. running with `@razeez/razeedeploy-core@0.13.1`, i get an identity object of `{ region: 'us-south' }`
2. running with `@razeez/razeedeploy-core@0.14.1`, i get an identity object of `{}`

investigating further
